### ISSUE TITLE
Fixes about camp leader -- Sign petition

### ISSUE THREAD

**Issue by sajid315** [the-canonizer/canonizer-3.0-frontend#1579]
As discussed in Morning Scrum Call of 22 Feb, we need to update following things regarding sign petition, 

- Sign button gray out instead of “you can’t delegate message from backend”, but from back-end we should restrict users.
- Add "No camp leader" option in the camp leader dropdown
- Add recent activity on new topic creation.
- Show some notes of current camp leader on form.
- Tooltip on camp leader icon.

**Comment by DevAlchemyCD** [comment]
@sajid315 return the nicknames in "/me" API.

**Comment by sajid315** [comment]
@wahaj-hafeez currently we are facing these kind of issues for exceptional cases as you can see in below screenshot. 
This screenshot is for the user who is logged out, 
Also we need to implement tooltip info's for the end users on sign petition,
![image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/111273633/86b69d0e-93a6-4aa4-b169-50f8a2fc0728)

**Comment by DevAlchemyCD** [comment]
@sajid315 ! The crashes are fixed & tooltip is added for the end users on the sign petition. The code is pushed on the branch "can-issue-1511". You can take pull and start working

**Comment by sajid315** [comment]
@wahaj-hafeez During testing we found another issue in case of "No Camp Leader" the notice is still showing. Have a look in below screenshot. 

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/111273633/0cd2faf7-8559-46b7-b1db-92d162bed4f6)

Also in case of "No Camp Leader" we should show text as "No" in front of (Camp Leader:).  This change should be on both pages , camp history and camp record of topic detail page.

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/111273633/221c310d-971c-4fbb-8f04-ca6892fb19e6)

**Comment by sajid315** [comment]
@wahaj-hafeez  Another error is also coming on sign camp button click,

![Image](https://github.com/the-canonizer/canonizer-3.0-frontend/assets/111273633/e1e5e9f0-72d5-42c7-93ea-4ecf92620344)

**Comment by wahaj-hafeez** [comment]
@sajid315 These issues are fixed now. You can take pull from branch "can-issue-1511" and verify.

**Comment by DevAlchemyCD** [comment]
@sajid315 These issues are fixed now. You can take pull from "can-issue-1511" and verify.
